import { useState } from "react";
import MenuCategories from "./MenuCategories";
import MenuItems from "./MenuItems";
import { BigTitle } from "./ui/Titles";

const Menu = () => {
  const items = [
    {
      id: 1,
      name: "BT Burger",
      price: 89.99,
      category: "burgers",
      image: "/assets/images/burger-1.jpg",
      imageDescription: "burger",
    },
    {
      id: 2,
      name: "Devil Side Burger",
      price: 35.25,
      category: "burgers",
      image: "/assets/images/burger-2.jpg",
      imageDescription: "burger",
    },
    {
      id: 3,
      name: "Bad Suns Burger",
      price: 49.99,
      category: "burgers",
      image: "/assets/images/burger-3.jpg",
      imageDescription: "burger",
    },
    {
      id: 4,
      name: "Heartbreaker Burger",
      price: 25.45,
      category: "burgers",
      image: "/assets/images/burger-4.jpg",
      imageDescription: "burger",
    },
    {
      id: 5,
      name: "Toma Burger",
      price: 81.59,
      category: "burgers",
      image: "/assets/images/burger-5.jpg",
      imageDescription: "burger",
    },
    {
      id: 6,
      name: "Mirage Burger",
      price: 104.27,
      category: "burgers",
      image: "/assets/images/burger-6.jpg",
      imageDescription: "burger",
    },
    {
      id: 7,
      name: "Burger of Eden",
      price: 19.99,
      category: "burgers",
      image: "/assets/images/burger-7.jpg",
      imageDescription: "burger",
    },
    {
      id: 8,
      name: "Robot Burger",
      price: 150.29,
      category: "burgers",
      image: "/assets/images/burger-8.jpg",
      imageDescription: "burger",
    },
    {
      id: 9,
      name: "Ivy Burger",
      price: 89.55,
      category: "burgers",
      image: "/assets/images/burger-9.jpg",
      imageDescription: "burger",
    },
    {
      id: 10,
      name: "Pity Pizza",
      price: 57.25,
      category: "pizzas",
      image: "/assets/images/pizza-1.jpg",
      imageDescription: "pizza",
    },
    {
      id: 11,
      name: "Years Pizza",
      price: 98.25,
      category: "pizzas",
      image: "/assets/images/pizza-2.jpg",
      imageDescription: "pizza",
    },
    {
      id: 12,
      name: "Pompeiizza",
      price: 45.95,
      category: "pizzas",
      image: "/assets/images/pizza-3.jpg",
      imageDescription: "pizza",
    },
    {
      id: 13,
      name: "Nightmare Pizza",
      price: 102.47,
      category: "pizzas",
      image: "/assets/images/pizza-4.jpg",
      imageDescription: "pizza",
    },
    {
      id: 14,
      name: "Cardi Bizza",
      price: 29.99,
      category: "pizzas",
      image: "/assets/images/pizza-5.jpg",
      imageDescription: "pizza",
    },
    {
      id: 15,
      name: "Midnights Pizza",
      price: 97.97,
      category: "pizzas",
      image: "/assets/images/pizza-6.jpg",
      imageDescription: "pizza",
    },
    {
      id: 16,
      name: "Icy Pizza",
      price: 57.25,
      category: "pizzas",
      image: "/assets/images/pizza-7.jpg",
      imageDescription: "pizza",
    },
    {
      id: 17,
      name: "Natalie Pizza",
      price: 55.99,
      category: "pizzas",
      image: "/assets/images/pizza-8.jpg",
      imageDescription: "pizza",
    },
    {
      id: 18,
      name: "Pizza Del Rey",
      price: 59.87,
      category: "pizzas",
      image: "/assets/images/pizza-9.jpg",
      imageDescription: "pizza",
    },
    {
      id: 19,
      name: "Spaghetti À La Moidé",
      price: 89.99,
      category: "pastas",
      image: "/assets/images/pasta-1.webp",
      imageDescription: "pasta",
    },
    {
      id: 20,
      name: "À La Tomatté",
      price: 104.25,
      category: "pastas",
      image: "/assets/images/pasta-2.webp",
      imageDescription: "pasta",
    },
    {
      id: 21,
      name: "Di Veganni",
      price: 285.89,
      category: "pastas",
      image: "/assets/images/pasta-3.webp",
      imageDescription: "pasta",
    },
    {
      id: 22,
      name: "Shoyu Showme",
      price: 107.48,
      category: "pastas",
      image: "/assets/images/pasta-5.webp",
      imageDescription: "pasta",
    },
    {
      id: 23,
      name: "Frutti Di Marí",
      price: 37.25,
      category: "pastas",
      image: "/assets/images/pasta-6.webp",
      imageDescription: "pasta",
    },
    {
      id: 24,
      name: "El Verdo",
      price: 455.87,
      category: "pastas",
      image: "/assets/images/pasta-7.webp",
      imageDescription: "pasta",
    },
    {
      id: 25,
      name: "Lavaggio",
      price: 57.88,
      category: "pastas",
      image: "/assets/images/pasta-8.webp",
      imageDescription: "pasta",
    },
    {
      id: 26,
      name: "Spratinno",
      price: 125.87,
      category: "pastas",
      image: "/assets/images/pasta-9.webp",
      imageDescription: "pasta",
    },
    {
      id: 27,
      name: "Partittian A Pa Vue",
      price: 88.89,
      category: "pastas",
      image: "/assets/images/pasta-10.webp",
      imageDescription: "pasta",
    },
    {
      id: 28,
      name: "Le Bruk",
      price: 83.27,
      category: "pastas",
      image: "/assets/images/pasta-11.webp",
      imageDescription: "pasta",
    },
    {
      id: 29,
      name: "Tittomino",
      price: 325.89,
      category: "pastas",
      image: "/assets/images/pasta-12.webp",
      imageDescription: "pasta",
    },
    {
      id: 30,
      name: "Envolvergannitto",
      price: 102.47,
      category: "vegan",
      image: "/assets/images/vegan-1.jpg",
      imageDescription: "vegan food",
    },
    {
      id: 31,
      name: "Baby Green Shades",
      price: 29.99,
      category: "vegan",
      image: "/assets/images/vegan-2.jpg",
      imageDescription: "vegan food",
    },
    {
      id: 32,
      name: "Green Light",
      price: 97.97,
      category: "vegan",
      image: "/assets/images/vegan-3.jpg",
      imageDescription: "vegan food",
    },
    {
      id: 33,
      name: "Rich Vegan Girls",
      price: 285.26,
      category: "vegan",
      image: "/assets/images/vegan-4.jpg",
      imageDescription: "vegan food",
    },
    {
      id: 34,
      name: "Rango",
      price: 123.45,
      category: "vegan",
      image: "/assets/images/vegan-5.jpg",
      imageDescription: "vegan food",
    },
    {
      id: 35,
      name: "Greenssoms",
      price: 77.97,
      category: "vegan",
      image: "/assets/images/vegan-6.jpg",
      imageDescription: "vegan food",
    },
    {
      id: 36,
      name: "Banana Splittus",
      price: 27.85,
      category: "desserts",
      image: "/assets/images/dessert-1.jpg",
      imageDescription: "dessert",
    },
    {
      id: 37,
      name: "Chocolatte Globe",
      price: 150.97,
      category: "desserts",
      image: "/assets/images/dessert-2.jpg",
      imageDescription: "dessert",
    },
    {
      id: 38,
      name: "Pie Nettone",
      price: 327.88,
      category: "desserts",
      image: "/assets/images/dessert-3.jpg",
      imageDescription: "dessert",
    },
    {
      id: 39,
      name: "Little Fruitty Pie",
      price: 77.97,
      category: "desserts",
      image: "/assets/images/dessert-4.jpg",
      imageDescription: "dessert",
    },
    {
      id: 40,
      name: "Square Frutitty Cake",
      price: 77.97,
      category: "desserts",
      image: "/assets/images/dessert-5.jpg",
      imageDescription: "dessert",
    },
    {
      id: 41,
      name: "Sweet Empadda",
      price: 23.97,
      category: "desserts",
      image: "/assets/images/dessert-6.jpg",
      imageDescription: "dessert",
    },
    {
      id: 42,
      name: "Flower Cupcake",
      price: 77.97,
      category: "desserts",
      image: "/assets/images/dessert-7.jpg",
      imageDescription: "dessert",
    },
    {
      id: 43,
      name: "Caramel Pie",
      price: 89.97,
      category: "desserts",
      image: "/assets/images/dessert-8.jpg",
      imageDescription: "dessert",
    },
    {
      id: 44,
      name: "Combo 1",
      price: 134.98,
      category: "combos",
      image: "/assets/images/combo-1.jpg",
      imageDescription: "combo with burger and fries",
    },
    {
      id: 45,
      name: "Combo 2",
      price: 150.58,
      category: "combos",
      image: "/assets/images/combo-2.jpg",
      imageDescription: "combo with burger and fries",
    },
    {
      id: 46,
      name: "Combo 3",
      price: 141.98,
      category: "combos",
      image: "/assets/images/combo-3.jpg",
      imageDescription: "combo with burger and fries",
    },
    {
      id: 47,
      name: "Combo 4",
      price: 108.98,
      category: "combos",
      image: "/assets/images/combo-4.jpg",
      imageDescription: "combo with burger and fries",
    },
    {
      id: 48,
      name: "Passion Fruit Juice",
      price: 25.98,
      category: "drinks",
      image: "/assets/images/drink-1.jpg",
      imageDescription: "passion fruit juice",
    },
    {
      id: 49,
      name: "Orange Juice",
      price: 30.0,
      category: "drinks",
      image: "/assets/images/drink-2.jpg",
      imageDescription: "orange juice",
    },
    {
      id: 50,
      name: "Strawberry Juice",
      price: 49.99,
      category: "drinks",
      image: "/assets/images/drink-3.jpg",
      imageDescription: "strawberry juice",
    },
    {
      id: 51,
      name: "Lemon Juice",
      price: 15.99,
      category: "drinks",
      image: "/assets/images/drink-4.jpg",
      imageDescription: "lemon juice",
    },
    {
      id: 52,
      name: "Fruit Mix Juice",
      price: 60.99,
      category: "drink",
      image: "/assets/images/drink-5.jpg",
      imageDescription: "fruit mix juice",
    },
  ];

  const [filteredItems, setFilteredItems] = useState([
    {
      id: 1,
      name: "BT Burger",
      price: 89.99,
      category: "burgers",
      image: "/assets/images/burger-1.jpg",
      imageDescription: "burger",
    },
    {
      id: 2,
      name: "Devil Side Burger",
      price: 35.25,
      category: "burgers",
      image: "/assets/images/burger-2.jpg",
      imageDescription: "burger",
    },
    {
      id: 3,
      name: "Bad Suns Burger",
      price: 49.99,
      category: "burgers",
      image: "/assets/images/burger-3.jpg",
      imageDescription: "burger",
    },
    {
      id: 4,
      name: "Heartbreaker Burger",
      price: 25.45,
      category: "burgers",
      image: "/assets/images/burger-4.jpg",
      imageDescription: "burger",
    },
    {
      id: 5,
      name: "Toma Burger",
      price: 81.59,
      category: "burgers",
      image: "/assets/images/burger-5.jpg",
      imageDescription: "burger",
    },
    {
      id: 6,
      name: "Mirage Burger",
      price: 104.27,
      category: "burgers",
      image: "/assets/images/burger-6.jpg",
      imageDescription: "burger",
    },
    {
      id: 7,
      name: "Burger of Eden",
      price: 19.99,
      category: "burgers",
      image: "/assets/images/burger-7.jpg",
      imageDescription: "burger",
    },
    {
      id: 8,
      name: "Robot Burger",
      price: 150.29,
      category: "burgers",
      image: "/assets/images/burger-8.jpg",
      imageDescription: "burger",
    },
    {
      id: 9,
      name: "Ivy Burger",
      price: 89.55,
      category: "burgers",
      image: "/assets/images/burger-9.jpg",
      imageDescription: "burger",
    },
  ]);

  return (
    <div className="flex flex-col justify-center items-center bg-lightRed pt-14 pb-28">
      <BigTitle title="Menu" marginTop="mt-12" />
      <MenuCategories items={items} filteredItemsSetter={setFilteredItems} />
      <MenuItems items={filteredItems} />
    </div>
  );
};

export default Menu;
